CREATE TABLE "books" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"word_count" integer NOT NULL,
	"cover_url" text NOT NULL,
	"bookid" text NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "books_bookid_idx" ON "books" USING btree ("bookid");
--> statement-breakpoint
CREATE INDEX "words_bookid_idx" ON "words" USING btree ("bookid");
--> statement-breakpoint
ALTER TABLE "words" ADD CONSTRAINT "words_bookid_books_bookid_fk" FOREIGN KEY ("bookid") REFERENCES "public"."books"("bookid") ON DELETE set null ON UPDATE cascade;
